name: Build ISPDB index

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate ispdb/index.html
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          mkdir -p ispdb

          out="ispdb/index.html"
          : > "$out"

          printf '%s\n' '<!doctype html>' >> "$out"
          printf '%s\n' '<html><head>' >> "$out"
          printf '%s\n' '  <meta charset="utf-8">' >> "$out"
          printf '%s\n' '  <title>ISPDB listing</title>' >> "$out"
          printf '%s\n' '  <style>body{font-family:system-ui,sans-serif;margin:2rem}ul{line-height:1.6}code{background:#f6f8fa;padding:.1rem .3rem;border-radius:.3rem}</style>' >> "$out"
          printf '%s\n' '</head><body>' >> "$out"
          printf '%s\n' '  <h1>ISPDB directory</h1>' >> "$out"
          printf '%s\n' '  <ul>' >> "$out"

          xmls=( ispdb/*.xml )
          if [ ${#xmls[@]} -eq 0 ]; then
            printf '%s\n' '    <li><em>No XML files found.</em></li>' >> "$out"
          else
            for p in "${xmls[@]}"; do
              f="${p##*/}"
              size="$(wc -c < "$p" | tr -d ' ')"
              printf '    <li><a href="%s">%s</a> <small><code>%s bytes</code></small></li>\n' "$f" "$f" "$size" >> "$out"
            done
          fi

          printf '%s\n' '  </ul>' >> "$out"
          printf '%s\n' '</body></html>' >> "$out"

      - name: Commit & push index
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pages): update ispdb index"
          file_pattern: "ispdb/index.html"
