name: Build folder index pages

on:
  push:
    branches:
      - master        # change to 'main' if that's your default
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-indexes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate index.html files (no heredocs)
        run: |
          set -euo pipefail

          gen_index () {
            dir="$1"
            [ -d "$dir" ] || return 0
            mkdir -p "$dir"

            # Gather .xml files (may be empty)
            mapfile -t files < <(printf '%s\n' "$dir"/*.xml 2>/dev/null | grep -E '\.xml$' || true)

            out="$dir/index.html"
            : > "$out"

            printf '%s\n' '<!doctype html>'                                   >> "$out"
            printf '%s\n' '<html>'                                            >> "$out"
            printf '%s\n' '<head>'                                            >> "$out"
            printf '%s\n' '  <meta charset="utf-8">'                          >> "$out"
            printf '%s\n' '  <title>ISPDB listing</title>'                    >> "$out"
            printf '%s\n' '  <style>'                                         >> "$out"
            printf '%s\n' '    body { font-family: system-ui, sans-serif; margin: 2rem; }' >> "$out"
            printf '%s\n' '    h1 { margin-bottom: .5rem; }'                  >> "$out"
            printf '%s\n' '    .hint { color: #555; margin-bottom: 1rem; }'   >> "$out"
            printf '%s\n' '    ul { line-height: 1.6; }'                      >> "$out"
            printf '%s\n' '    code { background: #f6f8fa; padding: .1rem .3rem; border-radius: .3rem; }' >> "$out"
            printf '%s\n' '  </style>'                                        >> "$out"
            printf '%s\n' '</head>'                                           >> "$out"
            printf '%s\n' '<body>'                                            >> "$out"
            printf '%s\n' '  <h1>ISPDB directory</h1>'                         >> "$out"
            printf '%s\n' '  <p class="hint">Static listing of available domain XML files.</p>' >> "$out"
            printf '%s\n' '  <ul>'                                            >> "$out"

            if [ "${#files[@]}" -gt 0 ]; then
              for path in "${files[@]}"; do
                file="$(basename "$path")"
                size="$(wc -c < "$path" | tr -d ' ')"
                printf '    <li><a href="%s">%s</a> <small><code>%s bytes</code></small></li>\n' "$file" "$file" "$size" >> "$out"
              done
            else
              printf '%s\n' '    <li><em>No XML files found.</em></li>'       >> "$out"
            fi

            printf '%s\n' '  </ul>'                                           >> "$out"
            printf '%s\n' '</body>'                                           >> "$out"
            printf '%s\n' '</html>'                                           >> "$out"
          }

          # Generate for whichever layout(s) you use
          gen_index autoconfig/ispdb
          gen_index autoconfig/v1.1

      - name: Commit & push index pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pages): update folder index pages"
          file_pattern: |
            autoconfig/ispdb/index.html
            autoconfig/v1.1/index.html
